### PR TITLE
Fix loading sos when kernel display name is not SoS #76

### PR DESCRIPTION
**Pull request by BoPeng**
#76

### CODE REVIEW

**Comment by gaow** [comment]
@BoPeng are we going to make another conda-forge release? We have the same issue with it on our end ...

**Comment by BoPeng** [comment]
I will but there is a pending issue for this version. I will make another release and craete a conda release after everything works.

**Comment by BoPeng** [comment]
jupyterlab 0.11.0 is released. I will make a conda release after a PR is created for it.

**Comment by BoPeng** [comment]
jupyterlab-sos 0.11.0 is released on conda-forge

**Pull request merged**
